apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf-container
          image: saiganesh03/a5gmicroservice-nrf
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nrf-service
spec:
  selector:
    app: nrf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
